### ISSUE TITLE
Console error with invalid P6 code

### ISSUE THREAD

**Issue by coke** [perl6/6pad#1]
The following code:

```
my @a = 1...Inf;
@a .= grep {$_ !%% 2};
say @a[^10];
```
Which has a syntax error (missing colon after the grep)

Causes a JS console error (at https://perl6.github.io/6pad/#2710b5f7dee79b6238eb586987a9d368)

```
Uncaught TypeError: nqp.op.cwd is not a function
```

(FYI, adding the colon back in seems to cause a hang)

**Comment by pmurias** [comment]
Syntax errors now print the same message as standard rakudo.js does (complete with ansi colors)
