### ISSUE TITLE
Code containing class can be executed only once.

### ISSUE THREAD

**Issue by bbkr** [perl6/6pad#2]
For example

```perl6
class A {};
say "witaj świecie";
```

Will work for the first time but when ran again without refreshing page it produces no output.
Precomp cleanup issue?

**Comment by pmurias** [comment]
EVAL being used causes a problem with an our class (my class works).
It's not yet clear what the proper solution is.

**Comment by jnthn** [comment]
@pmurias `EVAL` at Perl 6 level expects that it should be contributing to a shared `GLOBAL` (I mean, that's what global means). Maybe 6pad could obtain the compiler from the `nqp::getcomp('perl6')` interface and evaluate it with that? I *think* that will have a fresher idea of global.

**Comment by pmurias** [comment]
Solved the problem by just iterating over and cleaning up GLOBAL.
