### ISSUE TITLE
Wiki example is broken

### ISSUE THREAD

**Issue by deefco** [perl6/6pad#3]
https://github.com/perl6/6pad/wiki/Sharing-Guide

> Create a gist with main.p6, index.html (if needed), and styles.css (if needed).
> Direct 6Pad to the gist ID. For example, to view https://gist.github.com/2710b5f7dee79b6238eb586987a9d368 in 6Pad, use the URL https://perl6.github.io/6pad/#2710b5f7dee79b6238eb586987a9d368.

This is broken, I'm assuming / guessing because the gist uses a file called hello.p6 instead of main.p6?

**Comment by pmurias** [comment]
Thank you for reported, I fixed it.
