### ISSUE TITLE
Is eval_code.js a copy of rakudo.js?

### ISSUE THREAD

**Issue by deefco** [perl6/6pad#4]
If so, how do I build this / update it? Is this functionality provisioned? If not, would it be useful?

**Comment by pmurias** [comment]
It's a simple bundled Perl 6 script:
```
use MONKEY-SEE-NO-EVAL;

my $register := EVAL(:lang<JavaScript>, 'return (function(cb) {
    window.evalP6 = function(code) {
        cb(code);
    }
    return 1;
})');

$register(-> str $code {
    EVAL($code);
    CATCH {
        default {
            say($_.gist);
        }
    }
});
```

Once I'll release a new version of rakudo.js I'll put instructions how to build that.

**Comment by pmurias** [comment]
It's built from https://github.com/pmurias/create_eval_code_for_6pad
